before:
    hooks:
        - go mod tidy

builds:
    - main: ./cmd/vault2env.go
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin

archives:
    - format: tar.gz
      # this name template makes the OS and Arch compatible with the results of uname.
      name_template: >-
          {{ .ProjectName }}_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
          {{- if .Arm }}v{{ .Arm }}{{ end }}
      # use zip for windows archives
      format_overrides:
          - goos: windows
            format: zip
brews:
    - tap:
          owner: rmarganti
          name: homebrew-tap

      commit_author:
          name: rmarganti
          email: ryan.marganti@gmail.com

      homepage: 'https://github.com/rmarganti/vault2env'
      description: 'Sync secrets between Vault and an .env file'
      skip_upload: auto

checksum:
    name_template: 'checksums.txt'

snapshot:
    name_template: '{{ incpatch .Version }}-next'

changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=4 sw=2 tw=0 fo=cnqoj
